### ISSUE TITLE
The plugin does not support TLS v1.3?

### ISSUE THREAD

**Issue by timorpic** [shadowsocks/v2ray-plugin#57] opened 2019-03-01 15:43 UTC
The plugin does not support TLS v1.3?

**Comment by Love4Taylor** [comment] 2019-03-01 16:35
It depends on v2ray-core

**Comment by t1935111** [comment] 2019-06-07 13:32
Duplicate of #82

**Comment by moralrebuild** [comment] 2019-06-19 05:22
Any progress? v2ray-core already started to support TLS 1.3 from 4.18.1

**Comment by Mygod** [comment] 2019-06-20 13:57
e5ada30

**Closed by Mygod** 2019-06-20 13:57 UTC
